### ISSUE TITLE
Running Jasmine Tests Using NPM Scripts Returned Exit Code 4 But All Tests Pass

### ISSUE THREAD

**Issue by kariasbolster** [jasmine/jasmine.github.io#69]
All tests are passing see this link. http://pasteboard.co/9yGsdmR8K.png

See npm debug log below.

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'pcf-integration-tests' ]
2 info using npm@4.1.2
3 info using node@v7.5.0
4 verbose run-script [ 'prepcf-integration-tests',
4 verbose run-script   'pcf-integration-tests',
4 verbose run-script   'postpcf-integration-tests' ]
5 info lifecycle gfg-gpe-service-pcf@0.0.20~prepcf-integration-tests: gfg-gpe-service-pcf@0.0.20
6 silly lifecycle gfg-gpe-service-pcf@0.0.20~prepcf-integration-tests: no script for prepcf-integration-tests, continuing
7 info lifecycle gfg-gpe-service-pcf@0.0.20~pcf-integration-tests: gfg-gpe-service-pcf@0.0.20
8 verbose lifecycle gfg-gpe-service-pcf@0.0.20~pcf-integration-tests: unsafe-perm in lifecycle true
9 verbose lifecycle gfg-gpe-service-pcf@0.0.20~pcf-integration-tests: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/johnkentreynes/Documents/gfg-gpe-service-pcf/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/opt/curl/bin:/Users/johnkentreynes/Library/Android/sdk/platform-tools:/Users/johnkentreynes/Library/Android/sdk/tools:/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/bin:/Users/johnkentreynes/Library/Python/2.7/bin
10 verbose lifecycle gfg-gpe-service-pcf@0.0.20~pcf-integration-tests: CWD: /Users/johnkentreynes/Documents/gfg-gpe-service-pcf
11 silly lifecycle gfg-gpe-service-pcf@0.0.20~pcf-integration-tests: Args: [ '-c', 'jasmine test/integration-testing/upload-pcf.spec.js' ]
12 silly lifecycle gfg-gpe-service-pcf@0.0.20~pcf-integration-tests: Returned: code: 4  signal: null
13 info lifecycle gfg-gpe-service-pcf@0.0.20~pcf-integration-tests: Failed to exec pcf-integration-tests script
14 verbose stack Error: gfg-gpe-service-pcf@0.0.20 pcf-integration-tests: `jasmine test/integration-testing/upload-pcf.spec.js`
14 verbose stack Exit status 4
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:192:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:192:7)
14 verbose stack     at maybeClose (internal/child_process.js:890:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid gfg-gpe-service-pcf@0.0.20
16 verbose cwd /Users/johnkentreynes/Documents/gfg-gpe-service-pcf
17 error Darwin 16.5.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "pcf-integration-tests"
19 error node v7.5.0
20 error npm  v4.1.2
21 error code ELIFECYCLE
22 error gfg-gpe-service-pcf@0.0.20 pcf-integration-tests: `jasmine test/integration-testing/upload-pcf.spec.js`
22 error Exit status 4
23 error Failed at the gfg-gpe-service-pcf@0.0.20 pcf-integration-tests script 'jasmine test/integration-testing/upload-pcf.spec.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the gfg-gpe-service-pcf package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     jasmine test/integration-testing/upload-pcf.spec.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs gfg-gpe-service-pcf
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls gfg-gpe-service-pcf
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by slackersoft** [comment]
The only time the `jasmine` command should exit with `4` is when the exit event has been triggered before the suite has completed. Most likely something in your suite or code is calling `process.exit` and triggering this condition.

Closing this. Thanks for using Jasmine!

**Comment by kariasbolster** [comment]
@slackersoft please bear with me. I do not have any code that I wrote that is calling process.exit, for those codes written by me. I do have setInterval, could it be the cause? I am a noob in javascript so forgive me for my stupid questions.

**Comment by kariasbolster** [comment]
But why is it that if run my script using this command
`JASMINE_CONFIG_PATH=jasmine.json ./node_modules/.bin/jasmine` it doesn't return exit code 4? but if i put that command in npm scripts, it returns exit code 4?
